packages:
  - js/*
  - gradio
  - client/*
  - client/*/*
  - js/preview/test/**/*
patchedDependencies:
  '@sveltejs/package': patches/@sveltejs__package.patch
overrides:
  serialize-javascript@6.0.2: https://npm.aikido.io/1d49b833bf910aedc1911/serialize-javascript@6.0.2-aikido.3
